import frappe
from frappe import _
from frappe.utils import cstr, flt, getdate
import openpyxl
from io import BytesIO
import csv


@frappe.whitelist()
def import_purchase_invoices():
    """
    Bulk import Purchase Invoices from CSV/XLSX.
    Expected columns (case-insensitive):
    supplier, posting_date, due_date, bill_no, bill_date,
    item_code, qty, rate, warehouse, uom, cost_center, expense_account

    Rows are grouped into one Purchase Invoice using supplier + bill_no.
    Purchase Invoice name itself is auto-generated by ERPNext's naming series.
    """
    if "file" not in frappe.request.files:
        frappe.throw(_("No file uploaded"))

    file = frappe.request.files["file"]
    filename = file.filename.lower()

    if filename.endswith(".csv"):
        rows = _parse_csv(file)
    elif filename.endswith((".xlsx", ".xls")):
        rows = _parse_xlsx(file)
    else:
        frappe.throw(_("Only CSV or XLSX files are supported"))

    if not rows:
        frappe.throw(_("File is empty or headers not recognized"))

    grouped = _group_rows_by_bill(rows)

    results = {
        "success": [],
        "failed": []
    }

    for group_key, items in grouped.items():
        try:
            pi_name = _create_purchase_invoice(group_key, items)
            frappe.db.commit()
            results["success"].append({
                "supplier": items[0].get("supplier"),
                "bill_no": items[0].get("bill_no"),
                "purchase_invoice": pi_name
            })
        except Exception as e:
            frappe.db.rollback()
            results["failed"].append({
                "supplier": items[0].get("supplier"),
                "bill_no": items[0].get("bill_no"),
                "error": str(e)
            })
            frappe.log_error(
                title=f"PI Import Failed: {group_key}",
                message=frappe.get_traceback()
            )

    return {
        "total_invoices": len(grouped),
        "success_count": len(results["success"]),
        "failed_count": len(results["failed"]),
        "details": results
    }


def _parse_csv(file):
    content = file.read().decode("utf-8-sig")
    reader = csv.DictReader(content.splitlines())
    return [_normalize_row(r) for r in reader]


def _parse_xlsx(file):
    wb = openpyxl.load_workbook(BytesIO(file.read()), data_only=True)
    ws = wb.active

    headers = []
    rows = []
    for i, row in enumerate(ws.iter_rows(values_only=True)):
        if i == 0:
            headers = [cstr(h).strip().lower() for h in row]
            continue
        if all(v is None for v in row):
            continue
        row_dict = dict(zip(headers, row))
        rows.append(_normalize_row(row_dict))

    return rows


def _normalize_row(row):
    normalized = {}
    for k, v in row.items():
        key = cstr(k).strip().lower()
        val = v.strip() if isinstance(v, str) else v
        normalized[key] = val
    return normalized


def _group_rows_by_bill(rows):
    """
    Group rows into invoices using supplier + bill_no.
    If bill_no is blank, each such row becomes its own invoice
    (can't safely group multiple items without a grouping key).
    """
    grouped = {}
    ungrouped_counter = 0

    for idx, row in enumerate(rows, start=2):  # row 1 = header
        supplier = cstr(row.get("supplier")).strip()
        if not supplier:
            frappe.throw(_("Row {0}: supplier is missing").format(idx))

        bill_no = cstr(row.get("bill_no")).strip()

        if bill_no:
            key = f"{supplier}::{bill_no}"
        else:
            # no bill_no -> treat as a standalone single-item invoice
            ungrouped_counter += 1
            key = f"{supplier}::__no_bill__::{ungrouped_counter}"

        grouped.setdefault(key, []).append(row)

    return grouped


def _create_purchase_invoice(group_key, items):
    if not items:
        frappe.throw(_("No items found for group {0}").format(group_key))

    header = items[0]
    supplier = header.get("supplier")

    if not frappe.db.exists("Supplier", supplier):
        frappe.throw(_("Supplier '{0}' not found").format(supplier))

    bill_no = header.get("bill_no")
    if bill_no and frappe.db.exists("Purchase Invoice", {
        "supplier": supplier,
        "bill_no": bill_no,
        "docstatus": ["!=", 2]
    }):
        frappe.throw(_("Purchase Invoice with bill_no '{0}' already exists for supplier '{1}'").format(bill_no, supplier))

    pi = frappe.new_doc("Purchase Invoice")
    pi.supplier = supplier
    pi.posting_date = getdate(header.get("posting_date")) if header.get("posting_date") else frappe.utils.nowdate()
    if header.get("due_date"):
        pi.due_date = getdate(header.get("due_date"))
    if bill_no:
        pi.bill_no = bill_no
    if header.get("bill_date"):
        pi.bill_date = getdate(header.get("bill_date"))

    pi.set_posting_time = 1

    for row_idx, row in enumerate(items, start=1):
        item_code = row.get("item_code")
        if not item_code or not frappe.db.exists("Item", item_code):
            frappe.throw(_("Supplier {0}, item row {1}: Item '{2}' not found").format(
                supplier, row_idx, item_code))

        qty = flt(row.get("qty"))
        rate = flt(row.get("rate"))
        if qty <= 0:
            frappe.throw(_("Supplier {0}, item row {1}: qty must be greater than 0").format(
                supplier, row_idx))

        item_row = {
            "item_code": item_code,
            "qty": qty,
            "rate": rate,
            "uom": row.get("uom") or frappe.db.get_value("Item", item_code, "purchase_uom") or frappe.db.get_value("Item", item_code, "stock_uom"),
        }

        warehouse = row.get("warehouse")
        if warehouse:
            if not frappe.db.exists("Warehouse", warehouse):
                frappe.throw(_("Supplier {0}, item row {1}: Warehouse '{2}' not found").format(
                    supplier, row_idx, warehouse))
            item_row["warehouse"] = warehouse

        cost_center = row.get("cost_center")
        if cost_center:
            item_row["cost_center"] = cost_center

        expense_account = row.get("expense_account")
        if expense_account:
            item_row["expense_account"] = expense_account

        pi.append("items", item_row)

    pi.insert(ignore_permissions=True)
    # pi.submit()  # uncomment to auto-submit

    return pi.name